### ISSUE TITLE
Performance issue with large CMakeLists.txt files

### ISSUE THREAD

**Issue by Niluge-KiWi** [Lindydancer/cmake-font-lock#3]
Using current master version and a large CMakeLists.txt file, adding a new line starting with `set(` in the beginning of the file will make emacs use a lot of cpu on each key stroke until the `set(...)` block is closed.

This make this mode unusable in large projects as each new character typed takes a noticeable time to display (~100-300ms).

It's probably due to a whole buffer look ahead to find the closing `)`, but it's too costly.

It's easy to reproduce with CMake's own [CMakeLists.txt](https://raw.githubusercontent.com/Kitware/CMake/master/CMakeLists.txt):  add a `set(bla` on the first line, and continue typing new characters.

**Comment by Lindydancer** [comment]
Hi,

I will take a look at it. Most likely, it would be possible to limit the
search to the next (non-comment) unindented line. That would limit the
search to the current block, hopefully, that would speed up the matching in
most cases.

    -- Anders

**Comment by Niluge-KiWi** [comment]
Good idea !

Although it wouldn't work in a large nested section. But this could be
fixed by searching to the next same-level-indented line. I don't know if
its easy to do though..

Also, it wouldn't work with incorrectly indented files, but it's probably
not a real problem.
Le 26 août 2015 12:43 PM, "Anders Lindgren" <notifications@github.com> a
écrit :

**Comment by Lindydancer** [comment]
I think we should start by narrowing the search to the current block, this
is what Emacs does it many other programming languages. If speed still is
an issue after that, we can start looking at other solutions.

**Comment by Lindydancer** [comment]
Hi,

please try the version I uploaded. There is a significant speedup when I do
the "set(bla" test, both when at the beginning of the file, but also inside
large macros.

Thanks for finding and reporting this!

    -- Anders

**Comment by Niluge-KiWi** [comment]
Hi,

I tested with your new commit, version 0.1.2, and I confirm this fix the performance issue I saw in the explained scenario, and also in my original private scenario with another cmake file.

Thank you !

**Comment by Lindydancer** [comment]
Perfect!

Again, thanks for reporting this!

/ Anders
