### ISSUE TITLE
Using with font-lock-add-keywords breaks

### ISSUE THREAD

**Issue by nilsdeppe** [Lindydancer/cmake-font-lock#5]
Hi,

Thank you for the really awesome package! It is really great :)

I normally add some custom highlighting of keywords in prog-mode, eg FIXME, TODO. However, when I do that cmake-font-lock won't activate from the cmake-mode-hook, only if I call it manually. My current workaround solution is to not enable the keyword highlighting in cmake-mode:

```
;; Highlight some keywords in prog-mode
(add-hook 'prog-mode-hook
          (lambda ()
            ;; Highlighting in cmake-mode this way interferes with
            ;; cmake-font-lock, which is something I don't yet understand.
            (when (not (derived-mode-p 'cmake-mode))
              (font-lock-add-keywords
               nil
               '(("\\<\\(FIXME\\|TODO\\|BUG\\|DONE\\)" 1 font-lock-warning-face t)
                 )
               )
              )
            )
          )
```

So the steps I take are:
1. Start Emacs opening a CMakeLists.txt file
2. Using (message) I deteremined first the prog-mode-hook above is called, then the cmake-mode-hook is called
3. No cmake-font-lock
4. Run M-x cmake-font-lock-activate enables cmake-font-lock

Here is how I set up cmake-mode:

```
(use-package cmake-mode
  :ensure t
  :mode ("CMakeLists.txt" ".cmake")
  :hook (cmake-mode . (lambda ()
                        (add-to-list 'company-backends 'company-cmake)))
  :config
  (use-package cmake-font-lock
    :ensure t
    :defer t
    :commands (cmake-font-lock-activate)
    :hook (cmake-mode . (lambda ()
                          (message "\nActivating font lock?\n")
                          (cmake-font-lock-activate)))
    )
  )
```

Do you know why this is happening? It would be useful to note on the README that the above workaround is necessary to get cmake-font-lock to activate properly. :)

Thank you!

**Comment by Lindydancer** [comment]
Hi!

The `cmake-font-lock-activate` function replaces the existing font-lock
keywords defined by `cmake-mode`. When doing this, it will also overwrite
any user-defined font-lock keywords. Unfortunately, I can't think of a
clean way to implement this so that only the keywords defined by
`cmake-mode` is replaced.

One way to handle this on your side is to call `font-lock-add-keywords`
after you called `cmake-font-lock-activate`.

    -- Anders

**Comment by nilsdeppe** [comment]
Hi Anders,

That works perfectly! Thanks for the quick and helpful reply, and thank you again for the great package :)

Nils
